services:
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    user: 1026:100
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - ./prometheus:/prometheus:rw
    networks:
      - coin-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: 1026:100
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources:rw
    networks:
      - coin-network

networks:
  coin-network:
    external: true